[package]
name = "emela-fmt"
description = "構文木を整形して出力する"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
emela-syntax.workspace = true
pretty.workspace = true
rowan.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
